# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               septor.xyz
tagline:             'A rambling mess'
description:         'A devblog of sorts - discussing, displaying, and accepting feedback about my coding projects.'
url:                 http://septor.xyz
baseurl:             'http://septor.xyz'
paginate:            5

# About/contact
author:
  name:              Patrick Weaver
  url:               https://twitter.com/septor
  email:             patrickweaver@gmail.com

# Custom vars
version:             1.0.0
